const HomeActionTypes = {
     GET_ALL_PROPERTY: 'GET_ALL_PROPERTY',
     GET_ALL_PROPERTY_SUCCESS: 'GET_ALL_PROPERTY_SUCCESS',
     GET_ALL_PROPERTY_FAILED: 'GET_ALL_PROPERTY_FAILED',
  };
  
  export default HomeActionTypes;
  